# Maintainer Information
MAINTAINER       := kawkwa
MAINTAINER_EMAIL := carpentier.pf@gmail.com

# Package Origin Configuration
PKG_ORG         := kw
PKG_ORIGIN      := kakwa
GPG_KEY         := rpmbuildtool

# Repository Settings
DEB_REPO_COMPONENT := main



DEB_ALL_TARGETS := trixie:amd64 noble:amd64 trixie:arm64 noble:arm64 sid:amd64 sid:arm64
RPM_ALL_TARGETS :=

# Repository Configuration
define DEB_REPO_CONFIG
Origin: $(PKG_ORIGIN)
Label: $(PKG_ORIGIN)
Suite: $(DIST)
Codename: $(DIST)
Version: 3.1
Architectures: $(ARCH)
Components: $(DEB_REPO_COMPONENT)
Description: Repository containing misc packages
SignWith: $(GPG_KEY)
endef

export DEB_REPO_CONFIG 
