.\" rpm2archive - Converts Red Hat Package (RPM) to archive archive
.TH rpm2archive 8 "11 January 2001" "Red Hat, Inc."
.SH NAME
rpm2archive \- Extract archive archive from RPM Package Manager (RPM) package.
.SH SYNOPSIS
\fBrpm2archive\fP [filename] 
.SH DESCRIPTION
\fBrpm2archive\fP converts the .rpm file specified as a single argument
to a archive archive on standard out. If a '-' argument is given, an rpm stream
is read from standard in.

.br
.I "\fBrpm2archive rpm-1.1-1.i386.rpm\fP"
.br
.I "\fBrpm2archive - < glint-1.0-1.i386.rpm\fP"
.br
.I "\fBrpm2archive glint-1.0-1.i386.rpm | tar tvf -\fP"

.SH SEE ALSO
.IR rpm (8)
.SH AUTHOR
.nf
Erik Troan <ewt@redhat.com>
.fi
