#!/bin/sh

# A script to replicate Upstream's spec's %build and %install:

DESTDIR=$1

prefix="/usr"
bindir="$prefix/bin"
sbindir="$prefix/sbin" # No libexec
datadir="$prefix/share"
mandir="$datadir/man"
sysconfdir="/etc"
python_sitelib="/usr/lib/python3/dist-packages" # FIXME: hardcoding

version=@VERSION@


#########################################
# The %install script:
#########################################

install -d $DESTDIR$bindir
install -d $DESTDIR$sbindir
install mockchain $DESTDIR$bindir/mockchain
install py/mock.py $DESTDIR$sbindir/mock
ln -s consolehelper $DESTDIR$bindir/mock

install -d $DESTDIR$sysconfdir/pam.d
cp -a etc/pam/* $DESTDIR$sysconfdir/pam.d/

install -d $DESTDIR$sysconfdir/mock
cp -a etc/mock/* $DESTDIR$sysconfdir/mock/

install -d $DESTDIR$sysconfdir/security/console.apps/
cp -a etc/consolehelper/mock $DESTDIR$sysconfdir/security/console.apps/mock

install -d $DESTDIR$datadir/bash-completion/completions/
cp -a etc/bash_completion.d/* $DESTDIR$datadir/bash-completion/completions/
ln -s mock $DESTDIR$datadir/bash-completion/completions/mockchain

install -d $DESTDIR$sysconfdir/pki/mock
cp -a etc/pki/* $DESTDIR$sysconfdir/pki/mock/

# FIXME: python modules:
#install -d $DESTDIR%{python_sitelib}/
#cp -a py/mockbuild $DESTDIR%{python_sitelib}/

install -d $DESTDIR$mandir/man1
cp -a docs/mock.1 $DESTDIR$mandir/man1/

install -d $DESTDIR/var/lib/mock
install -d $DESTDIR/var/cache/mock

# just for %%ghosting purposes
ln -s fedora-rawhide-x86_64.cfg $DESTDIR$sysconfdir/mock/default.cfg
