#!/bin/bash
# example file to be used with --hookdir
#
# invoke shell if build fails.

BUILDDIR="${BUILDDIR:-/tmp/buildd}"

apt install -y "${APTGETOPT[@]}" vim less tree
cd "$BUILDDIR"/*/debian/..

/bin/bash < /dev/tty > /dev/tty 2> /dev/tty
